"""
Database utilities for Tonal Hortator.

This package contains centralized database queries, schema definitions,
and metadata mappings to keep the codebase clean and maintainable.
"""

from .metadata_mappings import MAPPING_CATEGORIES, METADATA_MAPPINGS
from .queries import (
    CHECK_TABLE_EXISTS,
    CHECK_TRACK_EXISTS,
    CREATE_METADATA_MAPPINGS_TABLE,
    CREATE_QUERY_LEARNING_TABLE,
    CREATE_TRACK_EMBEDDINGS_TABLE,
    CREATE_TRACK_RATINGS_TABLE,
    CREATE_TRACKS_TABLE,
    CREATE_USER_FEEDBACK_TABLE,
    CREATE_USER_PREFERENCES_TABLE,
    GET_EMBEDDING_STATS,
    GET_QUERY_LEARNING_DATA,
    GET_TRACK_RATINGS,
    GET_TRACKS_WITHOUT_EMBEDDINGS,
    GET_USER_FEEDBACK_STATS,
    GET_USER_PREFERENCES,
    INSERT_QUERY_LEARNING,
    INSERT_TRACK,
    INSERT_TRACK_EMBEDDING,
    INSERT_TRACK_RATING,
    INSERT_USER_FEEDBACK,
    INSERT_USER_PREFERENCE,
    UPDATE_QUERY_LEARNING_APPLIED,
)
from .schema import (
    METADATA_COLUMNS,
    QUERY_LEARNING_TABLE_SCHEMA,
    TRACK_RATINGS_TABLE_SCHEMA,
    TRACKS_TABLE_SCHEMA,
    USER_FEEDBACK_TABLE_SCHEMA,
    USER_PREFERENCES_TABLE_SCHEMA,
)

__all__ = [
    # Queries
    "CREATE_TRACKS_TABLE",
    "CREATE_TRACK_EMBEDDINGS_TABLE",
    "CREATE_METADATA_MAPPINGS_TABLE",
    "CREATE_USER_FEEDBACK_TABLE",
    "CREATE_USER_PREFERENCES_TABLE",
    "CREATE_TRACK_RATINGS_TABLE",
    "CREATE_QUERY_LEARNING_TABLE",
    "GET_TRACKS_WITHOUT_EMBEDDINGS",
    "INSERT_TRACK",
    "INSERT_TRACK_EMBEDDING",
    "INSERT_USER_FEEDBACK",
    "INSERT_USER_PREFERENCE",
    "INSERT_TRACK_RATING",
    "INSERT_QUERY_LEARNING",
    "UPDATE_QUERY_LEARNING_APPLIED",
    "GET_EMBEDDING_STATS",
    "GET_USER_FEEDBACK_STATS",
    "GET_USER_PREFERENCES",
    "GET_TRACK_RATINGS",
    "GET_QUERY_LEARNING_DATA",
    "CHECK_TABLE_EXISTS",
    "CHECK_TRACK_EXISTS",
    # Schema
    "TRACKS_TABLE_SCHEMA",
    "METADATA_COLUMNS",
    "USER_FEEDBACK_TABLE_SCHEMA",
    "USER_PREFERENCES_TABLE_SCHEMA",
    "TRACK_RATINGS_TABLE_SCHEMA",
    "QUERY_LEARNING_TABLE_SCHEMA",
    # Metadata mappings
    "METADATA_MAPPINGS",
    "MAPPING_CATEGORIES",
]
